# Generated by Django 2.2.2 on 2019-07-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_strategy_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy_pnl',
            name='pnl',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
